// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebProje.Migrations
{
    [DbContext(typeof(PostgreSqlDbContext))]
    [Migration("20241228151621_clearappointments")]
    partial class clearappointments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebProje.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentTime = new DateTime(2024, 12, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1000,
                            AppointmentTime = new DateTime(2024, 12, 30, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1001,
                            AppointmentTime = new DateTime(2024, 12, 30, 9, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1002,
                            AppointmentTime = new DateTime(2024, 12, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1003,
                            AppointmentTime = new DateTime(2024, 12, 30, 10, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1004,
                            AppointmentTime = new DateTime(2024, 12, 30, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1005,
                            AppointmentTime = new DateTime(2024, 12, 30, 11, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1006,
                            AppointmentTime = new DateTime(2024, 12, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1007,
                            AppointmentTime = new DateTime(2024, 12, 30, 12, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1008,
                            AppointmentTime = new DateTime(2024, 12, 30, 13, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1009,
                            AppointmentTime = new DateTime(2024, 12, 30, 13, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1010,
                            AppointmentTime = new DateTime(2024, 12, 30, 14, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1011,
                            AppointmentTime = new DateTime(2024, 12, 30, 14, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1012,
                            AppointmentTime = new DateTime(2024, 12, 30, 15, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1013,
                            AppointmentTime = new DateTime(2024, 12, 30, 15, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1014,
                            AppointmentTime = new DateTime(2024, 12, 30, 16, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1015,
                            AppointmentTime = new DateTime(2024, 12, 30, 16, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1016,
                            AppointmentTime = new DateTime(2024, 12, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1017,
                            AppointmentTime = new DateTime(2024, 12, 31, 9, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1018,
                            AppointmentTime = new DateTime(2024, 12, 31, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1019,
                            AppointmentTime = new DateTime(2024, 12, 31, 10, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1020,
                            AppointmentTime = new DateTime(2024, 12, 31, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1021,
                            AppointmentTime = new DateTime(2024, 12, 31, 11, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1022,
                            AppointmentTime = new DateTime(2024, 12, 31, 12, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1023,
                            AppointmentTime = new DateTime(2024, 12, 31, 12, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1024,
                            AppointmentTime = new DateTime(2024, 12, 31, 13, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1025,
                            AppointmentTime = new DateTime(2024, 12, 31, 13, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1026,
                            AppointmentTime = new DateTime(2024, 12, 31, 14, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1027,
                            AppointmentTime = new DateTime(2024, 12, 31, 14, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1028,
                            AppointmentTime = new DateTime(2024, 12, 31, 15, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1029,
                            AppointmentTime = new DateTime(2024, 12, 31, 15, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1030,
                            AppointmentTime = new DateTime(2024, 12, 31, 16, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1031,
                            AppointmentTime = new DateTime(2024, 12, 31, 16, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1032,
                            AppointmentTime = new DateTime(2025, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1033,
                            AppointmentTime = new DateTime(2025, 1, 1, 9, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1034,
                            AppointmentTime = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1035,
                            AppointmentTime = new DateTime(2025, 1, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1036,
                            AppointmentTime = new DateTime(2025, 1, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1037,
                            AppointmentTime = new DateTime(2025, 1, 1, 11, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1038,
                            AppointmentTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1039,
                            AppointmentTime = new DateTime(2025, 1, 1, 12, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1040,
                            AppointmentTime = new DateTime(2025, 1, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1041,
                            AppointmentTime = new DateTime(2025, 1, 1, 13, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1042,
                            AppointmentTime = new DateTime(2025, 1, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1043,
                            AppointmentTime = new DateTime(2025, 1, 1, 14, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1044,
                            AppointmentTime = new DateTime(2025, 1, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1045,
                            AppointmentTime = new DateTime(2025, 1, 1, 15, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1046,
                            AppointmentTime = new DateTime(2025, 1, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1047,
                            AppointmentTime = new DateTime(2025, 1, 1, 16, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1048,
                            AppointmentTime = new DateTime(2025, 1, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1049,
                            AppointmentTime = new DateTime(2025, 1, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1050,
                            AppointmentTime = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1051,
                            AppointmentTime = new DateTime(2025, 1, 2, 10, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1052,
                            AppointmentTime = new DateTime(2025, 1, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1053,
                            AppointmentTime = new DateTime(2025, 1, 2, 11, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1054,
                            AppointmentTime = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1055,
                            AppointmentTime = new DateTime(2025, 1, 2, 12, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1056,
                            AppointmentTime = new DateTime(2025, 1, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1057,
                            AppointmentTime = new DateTime(2025, 1, 2, 13, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1058,
                            AppointmentTime = new DateTime(2025, 1, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1059,
                            AppointmentTime = new DateTime(2025, 1, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1060,
                            AppointmentTime = new DateTime(2025, 1, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1061,
                            AppointmentTime = new DateTime(2025, 1, 2, 15, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1062,
                            AppointmentTime = new DateTime(2025, 1, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1063,
                            AppointmentTime = new DateTime(2025, 1, 2, 16, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1064,
                            AppointmentTime = new DateTime(2025, 1, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1065,
                            AppointmentTime = new DateTime(2025, 1, 3, 9, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1066,
                            AppointmentTime = new DateTime(2025, 1, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1067,
                            AppointmentTime = new DateTime(2025, 1, 3, 10, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1068,
                            AppointmentTime = new DateTime(2025, 1, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1069,
                            AppointmentTime = new DateTime(2025, 1, 3, 11, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1070,
                            AppointmentTime = new DateTime(2025, 1, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1071,
                            AppointmentTime = new DateTime(2025, 1, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1072,
                            AppointmentTime = new DateTime(2025, 1, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1073,
                            AppointmentTime = new DateTime(2025, 1, 3, 13, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1074,
                            AppointmentTime = new DateTime(2025, 1, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1075,
                            AppointmentTime = new DateTime(2025, 1, 3, 14, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1076,
                            AppointmentTime = new DateTime(2025, 1, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1077,
                            AppointmentTime = new DateTime(2025, 1, 3, 15, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1078,
                            AppointmentTime = new DateTime(2025, 1, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1079,
                            AppointmentTime = new DateTime(2025, 1, 3, 16, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1080,
                            AppointmentTime = new DateTime(2025, 1, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1081,
                            AppointmentTime = new DateTime(2025, 1, 4, 9, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1082,
                            AppointmentTime = new DateTime(2025, 1, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1083,
                            AppointmentTime = new DateTime(2025, 1, 4, 10, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1084,
                            AppointmentTime = new DateTime(2025, 1, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1085,
                            AppointmentTime = new DateTime(2025, 1, 4, 11, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1086,
                            AppointmentTime = new DateTime(2025, 1, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1087,
                            AppointmentTime = new DateTime(2025, 1, 4, 12, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1088,
                            AppointmentTime = new DateTime(2025, 1, 4, 13, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1089,
                            AppointmentTime = new DateTime(2025, 1, 4, 13, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1090,
                            AppointmentTime = new DateTime(2025, 1, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1091,
                            AppointmentTime = new DateTime(2025, 1, 4, 14, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1092,
                            AppointmentTime = new DateTime(2025, 1, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1093,
                            AppointmentTime = new DateTime(2025, 1, 4, 15, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1094,
                            AppointmentTime = new DateTime(2025, 1, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 1095,
                            AppointmentTime = new DateTime(2025, 1, 4, 16, 30, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            ServiceId = 1,
                            Status = false,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("WebProje.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mustafa Yılmaz",
                            Specialty = "Haircut",
                            WorkingHours = "9 am-5 pm"
                        });
                });

            modelBuilder.Entity("WebProje.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 30,
                            Name = "Haircut",
                            Price = 50.0
                        });
                });

            modelBuilder.Entity("WebProje.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "b22121210034@gmail.com",
                            Name = "Admin",
                            Password = "sau",
                            Role = "admin",
                            Surname = "User"
                        });
                });

            modelBuilder.Entity("WebProje.Models.Appointment", b =>
                {
                    b.HasOne("WebProje.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebProje.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebProje.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
